from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(frozen=True)
class CompetencyArea:
    id: str
    name: str
    description: str
    queries: tuple[str, ...]
    keywords: tuple[str, ...]
    related_tech: tuple[str, ...] = field(default_factory=tuple)


REQUIRED_AREAS: tuple[CompetencyArea, ...] = (
    CompetencyArea(
        id="python",
        name="Python",
        description="Python language use for AI/ML systems, tooling, APIs, and data work.",
        queries=(
            "Python programming experience, scripts, packages, FastAPI, Django, pytest",
            "built or maintained Python applications, data pipelines, or ML code",
        ),
        keywords=(
            "python",
            "pytest",
            "fastapi",
            "django",
            "flask",
            "pandas",
            "numpy",
            "asyncio",
            "poetry",
            "pip",
        ),
    ),
    CompetencyArea(
        id="llms",
        name="Large Language Models (LLMs)",
        description="Working with large language models: prompting, fine-tuning, evaluation, or production use.",
        queries=(
            "large language models LLM GPT Claude Llama prompting fine-tuning evaluation",
            "used or deployed language models in a product or research project",
        ),
        keywords=(
            "llm",
            "llms",
            "gpt",
            "chatgpt",
            "claude",
            "llama",
            "gemini",
            "mistral",
            "transformer",
            "prompt",
            "fine-tun",
            "instruction tun",
        ),
        related_tech=("openai", "anthropic", "huggingface transformers"),
    ),
    CompetencyArea(
        id="embeddings",
        name="Embeddings",
        description="Creating or using vector embeddings for similarity, search, or clustering.",
        queries=(
            "embeddings sentence-transformers word vectors cosine similarity embedding model",
            "generated embeddings for documents, search, or recommendation",
        ),
        keywords=(
            "embedding",
            "embeddings",
            "sentence-transformers",
            "word2vec",
            "sentencebert",
            "text-embedding",
            "vector representation",
        ),
    ),
    CompetencyArea(
        id="vector_databases",
        name="Vector databases",
        description="Storing and querying embedding vectors (FAISS, Chroma, Pinecone, Weaviate, pgvector, etc.).",
        queries=(
            "vector database FAISS Chroma Pinecone Weaviate Milvus pgvector Qdrant",
            "indexed vectors for similarity search or retrieval",
        ),
        keywords=(
            "faiss",
            "chroma",
            "chromadb",
            "pinecone",
            "weaviate",
            "milvus",
            "pgvector",
            "qdrant",
            "vector database",
            "vector store",
            "vector index",
        ),
    ),
    CompetencyArea(
        id="rag",
        name="Retrieval-Augmented Generation (RAG)",
        description="Pipelines that retrieve documents and condition an LLM on that context.",
        queries=(
            "retrieval augmented generation RAG chunking retriever rerank hybrid search",
            "built a RAG system that retrieves context for a language model",
        ),
        keywords=(
            "rag",
            "retrieval-augmented",
            "retrieval augmented",
            "retriever",
            "chunking",
            "rerank",
            "hybrid search",
        ),
    ),
    CompetencyArea(
        id="ml_dl",
        name="Machine Learning / Deep Learning",
        description="Classical ML or deep learning: training, evaluation, data, or model design.",
        queries=(
            "machine learning deep learning neural network training evaluation sklearn pytorch",
            "trained or evaluated models, datasets, metrics, experiments",
        ),
        keywords=(
            "machine learning",
            "deep learning",
            "neural network",
            "scikit-learn",
            "sklearn",
            "xgboost",
            "cnn",
            "rnn",
            "lstm",
            "gradient boosting",
            "supervised",
            "unsupervised",
            "classification",
            "regression",
        ),
        related_tech=(
            "pytorch",
            "tensorflow",
            "keras",
            "jax",
        ),
    ),
    CompetencyArea(
        id="ai_frameworks",
        name="AI frameworks and libraries",
        description="Frameworks such as PyTorch, TensorFlow, LangChain, LlamaIndex, Hugging Face, etc.",
        queries=(
            "PyTorch TensorFlow Keras LangChain LlamaIndex Hugging Face Transformers",
            "used AI or ML libraries to implement models or pipelines",
        ),
        keywords=(
            "pytorch",
            "tensorflow",
            "keras",
            "langchain",
            "llamaindex",
            "huggingface",
            "hugging face",
            "transformers",
            "jax",
            "onnx",
            "langgraph",
        ),
    ),
    CompetencyArea(
        id="model_apis",
        name="Model integration and APIs",
        description="Integrating model providers or serving models through APIs, SDKs, or inference services.",
        queries=(
            "OpenAI API Anthropic Azure OpenAI Bedrock Vertex AI model serving FastAPI inference",
            "integrated a model API or deployed an inference endpoint",
        ),
        keywords=(
            "openai",
            "openai api",
            "anthropic",
            "azure openai",
            "bedrock",
            "vertex ai",
            "inference",
            "model serving",
            "vllm",
            "triton",
            "model api",
            "llm api",
        ),
    ),
    CompetencyArea(
        id="ai_architecture",
        name="AI solution architecture",
        description="Design of end-to-end AI systems: data flow, evaluation, latency, cost, safety, orchestration.",
        queries=(
            "AI architecture system design orchestration agents evaluation observability pipelines",
            "designed an end-to-end AI solution including retrieval, models, and serving",
        ),
        keywords=(
            "architecture",
            "system design",
            "orchestration",
            "multi-agent",
            "agentic",
            "evaluation",
            "observability",
            "latency",
            "guardrail",
            "pipeline",
            "microservice",
        ),
    ),
)


# Technologies that may appear on CVs and should be captured as additional AI-relevant items.
ADDITIONAL_TECH_KEYWORDS: tuple[str, ...] = (
    "mlflow",
    "wandb",
    "weights & biases",
    "airflow",
    "kubeflow",
    "ray",
    "spark",
    "docker",
    "kubernetes",
    "onnx",
    "tensorrt",
    "whisper",
    "stable diffusion",
    "computer vision",
    "opencv",
    "nlp",
    "spacy",
    "nltk",
    "bert",
    "t5",
    "diffusion",
    "reinforcement learning",
    "rlhf",
    "lora",
    "qlora",
    "peft",
    "dspy",
    "autogen",
    "crewai",
    "semantic kernel",
    "haystack",
    "elasticsearch",
    "opensearch",
    "grafana",
    "prometheus",
    "langsmith",
    "ragas",
    "guardrails",
)
